active directory client is more generic
flsy/ldap-stub pull request #5
Opened 2020-10-20 10:31 UTC by dtourek

search function is now working and tested
Eslint fixes implementation

2020-10-20 10:52 UTC, kolebjak commented on src/activeDirectory/activeDirectoryServer.ts
> +    .map((a) => a.trim())
unnecessary double map. could be handled in one iteration.

2020-10-20 10:52 UTC, kolebjak commented on src/activeDirectory/activeDirectoryServer.ts
> +  const logger = adArgs.logger ? adArgs.logger : () => null;
```suggestion
  const logger = adArgs.logger ? adArgs.logger : console.log;
```

2020-10-20 11:34 UTC, dtourek commented on src/activeDirectory/activeDirectoryServer.ts
> +    .map((a) => a.trim())
fix in https://github.com/flsy/ldap-stub/pull/5/commits/ef3b2580faee13216d55bac8b7c29755f4ebc689

2020-10-20 11:35 UTC, dtourek commented on src/activeDirectory/activeDirectoryServer.ts
> +  const logger = adArgs.logger ? adArgs.logger : () => null;
fix in https://github.com/flsy/ldap-stub/pull/5/commits/ef3b2580faee13216d55bac8b7c29755f4ebc689

2020-10-20 14:49 UTC, smidhonza requested changes
Ahoj, prosimte rozdel ten pull request na dva, jeden kde mas ty zmeny co chces udelat a na druhej kde celej kod menis kvuli lintu a prettieru. Tomuhle se vazne neda rozumne udelat review kdyz kombinujes milion zmen do jednoho PR. dik

Vubec neni jasny o jaky zmeny tu vubec jde.

2020-10-20 14:49 UTC, smidhonza commented on src/activeDirectory/activeDirectoryServer.ts
> +      return dc.startsWith('dc=') ? dc : value;
ted se ta funkce chova ale trochu jinak, ne?

predtim:
`lovercaseDC('DC=Moje') vratilo 'dc=Moje';`

ted:
`lovercaseDC('DC=Moje') vrati 'dc=moje';`

je to tak dobre ?

2020-10-21 08:05 UTC, dtourek commented on src/activeDirectory/activeDirectoryServer.ts
> +      return dc.startsWith('dc=') ? dc : value;
jo chapu, on ten textovy retezec jeste pokracuje

2020-10-21 08:06 UTC, closed without merging