Improve search method + code cleanup
flsy/ldap-stub pull request #8
Opened 2020-11-03 14:37 UTC by dtourek

2020-11-03 15:00 UTC, kolebjak requested changes

2020-11-03 15:00 UTC, kolebjak commented on package.json
> +    "@typescript-eslint/eslint-plugin": "^4.5.0",
nevim jak se search metodou souvisí pluginy do eslintu.

2020-11-03 15:12 UTC, dtourek commented on package.json
> +    "@typescript-eslint/eslint-plugin": "^4.5.0",
nijak, merge conflict

2020-11-03 15:13 UTC, dtourek commented on src/methods.ts
> +  options.attributes.reduce((curr, acc) => {
ok

2020-11-03 15:13 UTC, dtourek commented on src/methods.ts
> +  }, {} as T);
ok

2020-11-03 15:20 UTC, kolebjak commented on package.json
> +    "@typescript-eslint/eslint-plugin": "^4.5.0",
v tom případě by to asi mělo jít pryč.

2020-11-03 15:42 UTC, dtourek commented on src/activeDirectory/activeDirectoryClient.ts
> -  search: async <T>(username: string, options: IOptions<T>): Promise<Either<Error, T[]>> => {
ok

2020-11-03 16:33 UTC, dtourek commented on src/interfaces.ts
> +  username?: string;
jsou pryc, protoze se vraci tak jak prijdou z ldapjs, cili ['CN=xxx',...] a jsou obsazeny uz v tom co mas v options. 

Tudiz nepotrebuji byt tady specifikovany, nicmene username vraci login().

2020-11-04 15:57 UTC, smidhonza approved these changes

2020-11-04 19:10 UTC, merged